baseURL = 'https://doowonee.com/'
defaultContentLanguage = "ko"
languageCode = 'ko-KR'
title = 'Doowonee'
theme = "paper"

[params]
favicon = "favicon.png"
appleTouchIcon = "favicon.png"

[permalinks]
posts = "/:slug/"
